WARNING  root:google_languages.py:74 Warning: Egyptian Arabic not found in the database for group Arabic.
INFO     lexiflux.signals:signals.py:55 Successfully created language preferences for user testuser (ID: 4)
INFO     lexiflux.signals:signals.py:55 Successfully created language preferences for user another_user (ID: 5)
INFO     root:reader_views.py:272 Location changed: book some-book-code, page 1, top word 10
ERROR    lexiflux.middleware:middleware.py:55 Exception: email does not have permission to read book '(ID: 4)
Traceback (most recent call last):
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/decorators.py", line 44, in wrapper
    return login_required(view_func)(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/views/reader_views.py", line 273, in location
    book = Book.get_if_can_be_read(request.user, code=book_code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/models.py", line 292, in get_if_can_be_read
    book.ensure_can_be_read_by(user)
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/models.py", line 275, in ensure_can_be_read_by
    raise PermissionDenied(
django.core.exceptions.PermissionDenied: email does not have permission to read book '(ID: 4)
WARNING  django.request:log.py:248 Forbidden: /location