INFO     root:apps.py:36 Lexiflux 2.6.0 is ready.
ERROR    root:google_languages.py:62 Skipping language group population.
Traceback (most recent call last):
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/apps/config.py", line 235, in get_model
    return self.models[model_name.lower()]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'languagegroup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/lexiflux/lexiflux/lexiflux/language/google_languages.py", line 60, in populate_language_groups
    language_group_class = get_model("lexiflux", "LanguageGroup")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/apps/registry.py", line 213, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lexiflux/lexiflux/.venv/lib/python3.12/site-packages/django/apps/config.py", line 237, in get_model
    raise LookupError(
LookupError: App 'lexiflux' doesn't have a 'LanguageGroup' model.
WARNING  root:google_languages.py:74 Warning: Egyptian Arabic not found in the database for group Arabic.
INFO     lexiflux.signals:signals.py:55 Successfully created language preferences for user testuser (ID: 1)
INFO     lexiflux.anki.anki_connect:anki_connect.py:83 result {'result': [1, 2, 3, 4, 5, 6]}